### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by ICDI0906** [Davidham3/STSGCN#1]
Hi~
thanks for your collected data, why is there 3 dimensions in pems08 and pems04 datasets, they are used to represent what?

**Comment by Davidham3** [comment]
@ICDI0906  Sorry, I've already forgot that, maybe flow, occupancy, speed. You can explore the PeMS website to figure out what do these three dimensions stand for.

**Comment by ICDI0906** [comment]
Ok, Thanks
